# Products

- title: Basetype
  url: https://github.com/drocarmo/basetype
  info: Modular typographic scale tool for your Sass workflow.

- title: Elenco
  url: http://drocarmo.com/elenco
  info: Chrome-extension designed to help you stay on track.

- title: Glob
  url: http://aglobof.github.io/
  info: Bower-managed packages of interface goodness ftw.

- title: Framer
  url: https://github.com/drocarmo/framer
  info: Prototypes I've built with Framer.js that you might find useful.

- title: Resources
  url: http://drocarmo.com/resources
  info: Library of resources that encompass the discipline of Product Design.

- title: Wheat
  url: http://drocarmo.com/wheat
  info: A Jekyll starter-template for designers.
