# Products

- title: Elenco
  url: http://drocarmo.com/elenco
  info: a chrome-extension designed to help you stay on track.

- title: Glob
  url: http://aglobof.github.io/
  info: bower-managed packages of interface goodness ftw.

- title: Framer
  url: https://github.com/drocarmo/framer
  info: prototypes built with Framer.js that you might find useful.

- title: Resources
  url: http://drocarmo.com/resources
  info: a library of resources on digital Product Design.

- title: Ritma
  url: http://drocarmo.com/ritma
  info: a personal exploration into creating art.

- title: Wheat
  url: http://drocarmo.com/wheat
  info: a Jekyll starter-template for designers.
